import * as vscode from "vscode"

type ProviderRequest =
  | { kind: "design"; payload: { goal?: string; preferredTemplate?: string } }
  | { kind: "improve"; payload: { filePath?: string; repairContext?: { problems?: Array<{ likelyFix?: string; message?: string; repairTarget?: string }> } } }
  | { kind: "explain"; payload: { repairContext?: { problems?: Array<{ likelyFix?: string; message?: string; repairTarget?: string }> } } }

export function activate(context: vscode.ExtensionContext): void {
  context.subscriptions.push(vscode.commands.registerCommand("sampleWorkflowAiProvider.provide", provideWorkflowAiOutput))
}

export function deactivate(): void {}

function provideWorkflowAiOutput(request: ProviderRequest): unknown {
  if (request.kind === "design") return designWorkflow(request.payload)
  if (request.kind === "improve") return improveWorkflow(request.payload)
  if (request.kind === "explain") return explainDiagnostics(request.payload)
  throw new Error("Unsupported workflow AI provider request kind.")
}

function designWorkflow(payload: { goal?: string; preferredTemplate?: string }) {
  const goal = payload.goal?.trim() || "Review the current workflow and produce a report."
  const name = goal.toLowerCase().replace(/[^a-z0-9._-]+/g, "-").replace(/-+/g, "-").replace(/^-+|-+$/g, "").slice(0, 48) || "sample-ai-workflow"
  return {
    name,
    title: titleFromName(name),
    description: goal,
    template: payload.preferredTemplate || (goal.toLowerCase().includes("report") ? "artifact-output" : "simple-agent"),
    notes: ["Generated by sampleWorkflowAiProvider.provide."]
  }
}

function improveWorkflow(payload: { filePath?: string; repairContext?: { problems?: Array<{ likelyFix?: string; message?: string; repairTarget?: string }> } }) {
  const problems = payload.repairContext?.problems ?? []
  return {
    summary: problems.length === 0 ? "No repair is needed." : `Found ${problems.length} issue(s) in ${payload.filePath ?? "the workflow"}.`,
    notes: problems.map((problem) => `${problem.repairTarget ?? "workflow"}: ${problem.likelyFix ?? problem.message ?? "Review this workflow section."}`)
  }
}

function explainDiagnostics(payload: { repairContext?: { problems?: Array<{ likelyFix?: string; message?: string; repairTarget?: string }> } }) {
  const problems = payload.repairContext?.problems ?? []
  return {
    summary: problems.length === 0 ? "No diagnostics to explain." : `Explained ${problems.length} diagnostic(s).`,
    items: problems.map((problem) => ({
      message: problem.message ?? "Workflow diagnostic",
      explanation: "The sample provider mirrors workflow-register repair context into a human-readable explanation.",
      likelyFix: problem.likelyFix,
      repairTarget: problem.repairTarget
    }))
  }
}

function titleFromName(name: string): string {
  return name.split(/[._-]+/).filter(Boolean).map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`).join(" ") || "Sample AI Workflow"
}
