param(
  [string]$Repo = "katamor1/ai-docs-c-large-project"
)

$labels = @(
  @{name="ai-docs"; color="5319e7"; description="AI documentation management"},
  @{name="ai-generated"; color="bfd4f2"; description="Generated by AI and not yet authoritative"},
  @{name="needs-human-review"; color="fbca04"; description="Human review required"},
  @{name="shared-memory"; color="c2e0c6"; description="Shared memory interface"},
  @{name="global-state"; color="d4c5f9"; description="Global variables and shared state"},
  @{name="dll-contract"; color="fef2c0"; description="DLL/API contract"},
  @{name="blocked"; color="b60205"; description="Blocked due to risk or insufficient evidence"},
  @{name="accepted"; color="0e8a16"; description="Accepted after review"}
)

foreach ($label in $labels) {
  gh label create $label.name --repo $Repo --color $label.color --description $label.description --force
}
