export function renderWorkflowBuilderGuidedHelpScript(): string {
  return String.raw`
function optionLabel(value, description) { return value ? value + ' — ' + description : '(未選択)'; }
function stepOptionLabel(id) { if (!id) return '(未選択)'; const step = model.steps.find(function(candidate) { return candidate.id === id; }); if (!step) return id + ' — 存在しない step'; return id + ' — ' + (step.title || step.id) + ' / ' + step.type; }
function resultKeyOptionLabel(key) { if (!key) return '(未選択)'; const step = model.steps.find(function(candidate) { return candidate.resultKey === key; }); if (!step) return key; return key + ' — ' + (step.title || step.id) + ' / ' + step.type; }
function stepTypeGuideHtml(type) { const guides = { agent: ['Prompt に Bob へ依頼する分析・生成内容を書く。', '前段結果が必要なら includeState を選ぶ。', '後続で使う出力なら resultKey を設定する。'], command: ['action.provider を選ぶ。', 'VS Code command ID / args[0] と extra args を指定する。', '結果を後続で使うなら resultKey と sendResult を設定する。', '成功時に自動で進めるなら completeOnSuccess を有効にする。'], manual: ['Prompt に人間へ確認してほしい内容を書く。', '必要なら includeState で前段結果を見せる。', '人間が完了するまで workflow を止める確認点として使う。'], result: ['source を選ぶ。', 'state の場合は stateKey を選ぶ。', 'literal の場合は literal text を入力する。', 'file sink path に保存先を書く。', '必要なら Artifacts タブで producedBy にこの step を指定する。'] }; const items = guides[type] || guides.agent; return '<div class="card help-inline-guide" data-help-id="step.type"><strong>' + escapeHtml(type) + ' step の設定ガイド</strong><ol>' + items.map(function(item) { return '<li>' + escapeHtml(item) + '</li>'; }).join('') + '</ol></div>'; }
function diagnosticTargetStep(line) { const match = String(line).match(/Step '([^']+)'/); if (!match) return -1; return model.steps.findIndex(function(step) { return step.id === match[1]; }); }
function diagnosticTarget(line) { const text = String(line || ''); const stepIndex = diagnosticTargetStep(text); if (/includeState/.test(text)) return { tab: 'step', helpId: 'step.includeState', stepIndex: stepIndex }; if (/resultKey/.test(text)) return { tab: 'step', helpId: 'step.resultKey', stepIndex: stepIndex }; if (/producedBy/.test(text) || /Artifact/.test(text)) return { tab: 'artifacts', helpId: 'artifact.producedBy' }; if (/allowedCommands|deniedCommands|guardrails/.test(text)) return { tab: 'guardrails', helpId: 'guardrails.allowedCommands' }; if (/options/.test(text)) return { tab: 'inputs', helpId: 'input.options' }; if (/files/.test(text)) return { tab: 'requires', helpId: 'requires.files' }; if (stepIndex >= 0) return { tab: 'step', helpId: 'step.id', stepIndex: stepIndex }; return undefined; }
function diagnosticLinkHtml(target, label) { if (!target || !target.helpId) return ''; return ' <button class="link" data-action="goto-help-target" data-tab="' + escapeHtml(target.tab || '') + '" data-help-id="' + escapeHtml(target.helpId) + '" data-index="' + escapeHtml(target.stepIndex === undefined ? '' : target.stepIndex) + '">[' + escapeHtml(label || 'この設定を確認') + ']</button>'; }
function renderDiagnosticsList() { return latestDiagnostics.map(function(line) { const target = diagnosticTarget(line); if (target) return '<li>' + escapeHtml(line) + diagnosticLinkHtml(target, '関連設定へ移動') + '</li>'; return '<li>' + escapeHtml(line) + '</li>'; }).join(''); }
function gotoHelpTarget(target) { if (target.dataset.index !== '') selectedStepIndex = Number(target.dataset.index); if (target.dataset.tab) activeTab = target.dataset.tab; render(); setTimeout(function() { if (window.workflowBuilderJumpToHelp) window.workflowBuilderJumpToHelp(target.dataset.helpId); }, 0); }
`
}
