export function renderWorkflowBuilderPreviewScript(): string {
  return String.raw`
function diagnosticTargetStep(line) { const match = String(line).match(/Step '([^']+)'/); if (!match) return -1; return model.steps.findIndex(function(step) { return step.id === match[1]; }); }
function diagnosticTarget(line) { const text = String(line || ''); const stepIndex = diagnosticTargetStep(text); if (/includeState/.test(text)) return { tab: 'step', helpId: 'step.includeState', stepIndex: stepIndex }; if (/resultKey/.test(text)) return { tab: 'step', helpId: 'step.resultKey', stepIndex: stepIndex }; if (/producedBy/.test(text) || /Artifact/.test(text)) return { tab: 'artifacts', helpId: 'artifact.producedBy' }; if (/allowedCommandIds|deniedCommandIds|command id/i.test(text)) return { tab: 'guardrails', helpId: 'guardrails.allowedCommandIds' }; if (/allowedCommands|deniedCommands|guardrails/.test(text)) return { tab: 'guardrails', helpId: 'guardrails.allowedCommands' }; if (/options/.test(text)) return { tab: 'inputs', helpId: 'input.options' }; if (/files/.test(text)) return { tab: 'requires', helpId: 'requires.files' }; if (stepIndex >= 0) return { tab: 'step', helpId: 'step.id', stepIndex: stepIndex }; return undefined; }
function diagnosticLinkHtml(target, label) { if (!target || !target.helpId) return ''; return ' <button class="link" data-action="goto-help-target" data-tab="' + escapeHtml(target.tab || '') + '" data-help-id="' + escapeHtml(target.helpId) + '" data-index="' + escapeHtml(target.stepIndex === undefined ? '' : target.stepIndex) + '">[' + escapeHtml(label || 'この設定を確認') + ']</button>'; }
function renderDiagnosticsList() { const diagnostics = editorDiagnostics.map(function(item) { return '- editor: ' + item.message; }).concat(latestDiagnostics); return diagnostics.map(function(line) { const target = diagnosticTarget(line); if (target) return '<li>' + escapeHtml(line) + diagnosticLinkHtml(target, '関連設定へ移動') + '</li>'; return '<li>' + escapeHtml(line) + '</li>'; }).join(''); }
function transitionSummaryHtml() { const rows = []; model.steps.forEach(function(step, index) { const transition = step.transition || {}; (Array.isArray(transition.decisions) ? transition.decisions : []).forEach(function(decision) { const targetIndex = model.steps.findIndex(function(candidate) { return candidate.id === decision.goto; }); const direction = targetIndex >= 0 && targetIndex <= index ? 'back' : 'forward'; rows.push('<li>' + escapeHtml(step.id) + ' -> ' + escapeHtml(decision.goto || '(missing)') + ' <span class="badge">' + escapeHtml(direction) + '</span>' + (decision.loop ? ' loop=' + escapeHtml(decision.loop) : '') + '</li>'); }); }); if (rows.length === 0) return '<div class="card transition-preview"><strong>Transition preview</strong><div class="muted">transition decisions are not defined.</div></div>'; return '<div class="card transition-preview"><strong>Transition preview</strong><ul class="issue-list">' + rows.join('') + '</ul></div>'; }
function renderPreview() { const issues = analyzeReferences(); const issueHtml = issues.length === 0 ? '<div class="card reference-ok"><strong>参照チェック OK</strong></div>' : '<div class="card reference-issue"><strong>参照チェック</strong><ul class="issue-list">' + issues.map(function(issue) { return '<li>' + escapeHtml(issue.message) + diagnosticLinkHtml(issue, 'この設定を確認') + '</li>'; }).join('') + '</ul></div>'; const diffButton = editMode ? '<button class="secondary" data-action="diff">Show Diff</button>' : ''; const pathLine = latestFilePath ? '<div class="muted">target: ' + escapeHtml(latestFilePath) + '</div>' : ''; const ok = latestOk && editorDiagnostics.length === 0; document.getElementById('content').innerHTML = '<h2>Preview / Diagnostics</h2><button data-action="validate">Validate</button>' + diffButton + '<button data-action="save">Save WORKFLOW.md</button>' + pathLine + issueHtml + transitionSummaryHtml() + '<div class="card diagnostics ' + (ok ? 'ok' : 'ng') + '"><strong>' + (ok ? 'Validation OK' : 'Validation has errors/warnings') + '</strong><ul class="issue-list">' + renderDiagnosticsList() + '</ul></div><h3>YAML / Markdown Preview</h3><pre>' + escapeHtml(latestPreview) + '</pre>'; }
`
}
