const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")
const { test } = require("node:test")

const repoRoot = path.resolve(__dirname, "..", "..", "..")
const scriptPath = path.join(repoRoot, "docs", "workflows", "code-consistency-review", "integration", "launch-bob-code-consistency-sandbox.ps1")

test("integration sandbox launcher uses Bob as an extension development path", () => {
  const script = fs.readFileSync(scriptPath, "utf8")

  assert.match(script, /Join-Path \$PSScriptRoot "\.\.\\\.\.\\\.\.\\\.\."/)
  assert.match(script, /\[ValidateSet\("simple-timeout-bugfix",\s*"ai-verification-matrix",\s*"live-traceability-sidecar"\)\]/)
  assert.match(script, /\[string\]\$Sample = "simple-timeout-bugfix"/)
  assert.match(script, /Initialize-AiVerificationMatrixWorkspace/)
  assert.match(script, /Initialize-LiveTraceabilitySidecarWorkspace/)
  assert.match(script, /Push-Location -LiteralPath \$WorkingDirectory/)
  assert.match(script, /Invoke-CheckedCommand \(Resolve-CommandPath "git"\) @\("init"/)
  assert.match(script, /switch",\s*"-c",\s*"feature\/ai-verification-matrix"/)
  assert.match(script, /switch",\s*"-c",\s*"feature\/live-traceability-sidecar"/)
  assert.match(script, /bob2[\\/]bob-code/)
  assert.match(script, /--extensionDevelopmentPath/)
  assert.match(script, /workflow-register-0\.1\.0\.vsix/)
  assert.match(script, /bob-bazaar-review-0\.3\.0\.vsix/)
  assert.match(script, /bob-code-consistency-review-0\.1\.0\.vsix/)
  assert.match(script, /bob-workflow-integration-/)
  assert.doesNotMatch(script, /Copy-Item[^\r\n]*bob2[\\/]bob-code/)
  assert.doesNotMatch(script, /WindowStyle\s+Hidden/)
})
