import { WorkflowAiDesignInput, WorkflowAiExplainInput, WorkflowAiProvider, WorkflowAiRepairInput, WorkflowDiagnosticExplanation, WorkflowRepairProposal } from "./workflowAiProvider"
import { WorkflowDesignDraft } from "./workflowDesignDraft"
import { WorkflowTemplateKind } from "./workflowScaffold"

export function createMockWorkflowAiProvider(): WorkflowAiProvider {
  return new MockWorkflowAiProvider()
}

class MockWorkflowAiProvider implements WorkflowAiProvider {
  readonly id = "mock-workflow-ai-provider"

  designWorkflow(input: WorkflowAiDesignInput): WorkflowDesignDraft {
    const template = input.preferredTemplate ?? chooseTemplateFromGoal(input.goal)
    const title = titleFromGoal(input.goal)
    return {
      name: nameFromGoal(input.goal),
      title,
      description: input.goal.trim() || `Run ${title}.`,
      template,
      notes: [
        `Generated by ${this.id}.`,
        "This is a deterministic mock draft; validate and replace example command ids before runtime execution."
      ]
    }
  }

  improveWorkflow(input: WorkflowAiRepairInput): WorkflowRepairProposal {
    if (input.repairContext.status === "valid") {
      return {
        summary: "The workflow is valid. No replacement is proposed by the mock provider.",
        notes: ["Use runtime diagnostics if the workflow validates but fails during execution."]
      }
    }
    return {
      summary: `Found ${input.repairContext.problems.length} problem(s) in ${input.filePath}.`,
      notes: input.repairContext.problems.map((problem) => `${problem.repairTarget ?? "workflow"}: ${problem.likelyFix ?? problem.message}`)
    }
  }

  explainDiagnostics(input: WorkflowAiExplainInput): WorkflowDiagnosticExplanation {
    return {
      summary: input.repairContext.problems.length === 0
        ? "No workflow diagnostics were found."
        : `Explained ${input.repairContext.problems.length} workflow diagnostic(s).`,
      items: input.repairContext.problems.map((problem) => ({
        message: problem.message,
        explanation: explanationForTarget(problem.repairTarget),
        likelyFix: problem.likelyFix,
        repairTarget: problem.repairTarget
      }))
    }
  }
}

export function chooseTemplateFromGoal(goal: string): WorkflowTemplateKind {
  const value = goal.toLowerCase()
  if (value.includes("review")) return "review-workflow"
  if (value.includes("artifact") || value.includes("report") || value.includes("document")) return "artifact-output"
  if (value.includes("input") || value.includes("parameter") || value.includes("option")) return "input-driven-agent"
  if (value.includes("safe") || value.includes("guard")) return "guarded-command"
  if (value.includes("command") || value.includes("collect")) return "command-then-agent"
  if (value.includes("checklist") || value.includes("manual")) return "manual-checklist"
  return "simple-agent"
}

function nameFromGoal(goal: string): string {
  return goal.toLowerCase().replace(/[^a-z0-9._-]+/g, "-").replace(/-+/g, "-").replace(/^-+|-+$/g, "").slice(0, 48) || "ai-designed-workflow"
}

function titleFromGoal(goal: string): string {
  const name = nameFromGoal(goal)
  return name.split(/[._-]+/).filter(Boolean).slice(0, 8).map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`).join(" ") || "AI Designed Workflow"
}

function explanationForTarget(target: string | undefined): string {
  if (target === "steps[].includeState") return "A step is trying to read workflow state that no earlier step currently produces."
  if (target === "steps[].result.stateKey") return "A result step is trying to write a state value that is missing from the run state."
  if (target === "steps[].id") return "Step ids are stable references and must be unique."
  if (target === "inputs.*.options") return "Select inputs need explicit options so the UI can present valid choices."
  if (target === "artifacts[].producedBy") return "Artifacts should point to the step that creates or writes them."
  if (target === "steps[].action.provider") return "Command steps need a registered action provider before they can run."
  if (target === "guardrails.allowedCommands/deniedCommands") return "A command cannot be simultaneously allowed and denied."
  if (target === "YAML front matter") return "The workflow parser reads metadata from the Markdown YAML front matter block."
  return "This diagnostic points to a workflow authoring issue that should be fixed before execution."
}
