const assert = require("node:assert/strict")
const { test } = require("node:test")
const { readSourceSet } = require("./helpers/sourceReader")

test("Bazaar workflow provider resolves repository root independently from workflowRoot", () => {
  const bridgeSource = readSourceSet(["workflow/workflowRegisterBridge.ts", "workspace/workspaceResolver.ts"])
  const guiSource = readSourceSet(["ui/reviewGui.ts", "ui/reviewGuiTypes.ts"])

  assert.match(bridgeSource, /workflowRoot\?: string/)
  assert.match(bridgeSource, /bazaarRoot\?: string/)
  assert.match(bridgeSource, /repositoryRoot\?: string/)
  assert.match(bridgeSource, /const explicitBazaarRoot =[\s\S]*stringInput\(input\?\.bazaarRoot\)[\s\S]*stringInput\(input\?\.repositoryRoot\)/)
  assert.match(bridgeSource, /bazaarRoot: explicitBazaarRoot/)
  assert.match(guiSource, /private bazaarWorkspaceFolder\?: vscode\.WorkspaceFolder/)
  assert.match(guiSource, /private bobWorkspaceFolder\?: vscode\.WorkspaceFolder/)
  assert.match(guiSource, /resolveBazaarWorkspaceFolder\(\{[\s\S]*workflowRoot: this\.initialTarget\?\.workflowRoot/)
  assert.match(guiSource, /resolveBobWorkspaceFolder\(\{[\s\S]*workflowRoot: this\.initialTarget\?\.workflowRoot/)
  assert.match(guiSource, /buildProjectRulesSectionForWorkspace\(bobFolder\.uri\.fsPath\)/)
  assert.doesNotMatch(guiSource, /workspaceFolders\?\.\[0\]|workspaceFolders\?\[0\]/)
})

test("Bazaar review GUI accepts workflow inputs as initial target values", () => {
  const bridgeSource = readSourceSet(["workflow/workflowRegisterBridge.ts"])
  const guiSource = readSourceSet(["ui/reviewGui.ts", "ui/reviewGuiHtml.ts", "ui/reviewGuiHtmlAssets.ts", "ui/reviewGuiTypes.ts"])

  assert.match(bridgeSource, /function initialTargetFromWorkflowInputs\(inputs: Record<string, unknown>, input\?: WorkflowActionExecutionInput\)/)
  assert.match(bridgeSource, /revisionMode: targetMode\(inputs\.revisionMode\)/)
  assert.match(bridgeSource, /runId: stringInput\(input\?\.runId\)/)
  assert.match(bridgeSource, /stepId: stringInput\(input\?\.stepId\)/)
  assert.match(guiSource, /export interface BazaarReviewInitialTarget/)
  assert.match(guiSource, /runId\?: string/)
  assert.match(guiSource, /stepId\?: string/)
  assert.match(guiSource, /openBazaarReviewGui\(context: vscode\.ExtensionContext, initialTarget\?: BazaarReviewInitialTarget\)/)
  assert.match(guiSource, /new BazaarReviewGuiController\(context, panel, initialTarget\)/)
  assert.match(guiSource, /const initialTargetJson = JSON\.stringify\(initialTarget \?\? \{\}\)/)
  assert.match(guiSource, /applyInitialTarget\(initialTarget\)/)
  assert.match(guiSource, /completeCurrentWorkflowStepAfterGuiAction\([\s\S]*\{[\s\S]*runId: this\.initialTarget\?\.runId[\s\S]*stepId: this\.initialTarget\?\.stepId[\s\S]*\}/)
  assert.match(guiSource, /REVIEW_PACKET_STATE_KEY/)
  assert.match(guiSource, /stateUpdates: \{[\s\S]*\[REVIEW_PACKET_STATE_KEY\]: JSON\.stringify\(/)
})
